@domain=47q45gwl-5001.use.devtunnels.ms

GET https://{{domain}}/.well-known/webfinger

###
GET https://{{domain}}/api/notes/4844caf4527247b5ae18dd3ecd207631

###
GET https://thedasblog.com/api/notes/518b8b08-2eea-4848-bf26-4b94b7b9abe9
Accept: application/activity+json

###
GET https://thedasblog.com/api/notes/518b8b082eea4848bf264b94b7b9abe9
Accept: application/activity+json

###
GET https://{{domain}}/@blog

###
GET https://{{domain}}/api/outbox


### Reply request
POST https://{{domain}}/api/inbox
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://dotnet.social/users/poppastring/statuses/112281648967418926/activity",
  "type": "Create",
  "actor": "https://dotnet.social/users/poppastring",
  
}

### Follow request
POST https://{{domain}}/api/inbox
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://mastodon.social/64527582-3605-4d19-ac99-6715df3b0707",
  "type": "Follow",
  "actor": "https://dotnet.social/users/poppastring",
  "object": "https://{{domain}}/@blog"
}

### Unfollow request
POST https://{{domain}}/api/inbox
{ 
  "@context":"https://www.w3.org/ns/activitystreams",
  "id":"https://dotnet.social/users/poppastring#follows/51971777/undo",
  "type":"Undo",
  "actor":"https://dotnet.social/users/poppastring",
  "object":{
    "id":"https://poppastring.social/f722c435-5a8a-4e94-b7c8-529cdcdf12a6",
    "type":"Follow",
    "actor":"https://dotnet.social/users/poppastring",
    "object":"https://{{domain}}/@blog"
  }
}

### Like post
POST https://{{domain}}/api/inbox
Accept: application/activity+json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://mastodon.social/64527582-3605-4d19-ac99-6715df3b0707",
  "type": "Like",
  "actor": "https://dotnet.social/users/poppastring",
  "object": "https://{{domain}}/@blog"
}