@hostname=localhost
@port=5001
@account=@mark@poppastring.com
@user=mark

GET https://{{hostname}}:{{port}}/.well-known/webfinger?resource=acct:{{account}}
Accept: application/jrd+json

###
GET https://{{hostname}}:{{port}}/users/{{user}}/outbox?page=true
Accept: application/jrd+json


