@hostname=localhost
@port=5001
@account=@mark@jvvp78jc-5001.use.devtunnels.ms
@user=mark

GET https://{{hostname}}:{{port}}/.well-known/webfinger?resource=acct:{{account}}
Accept: application/jrd+json

###
GET https://{{hostname}}:{{port}}/users/{{user}}/outbox?page=true
Accept: application/jrd+json

###
GET https://jvvp78jc-5001.use.devtunnels.ms/users/{{user}}/outbox?page=false
Accept: application/jrd+json