//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace newtelligence.DasBlog.Web.Services.Test.ConfigService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfigEditingServiceSoap", Namespace="urn:schemas-newtelligence-com:dasblog:config-services")]
    public partial class ConfigEditingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private authenticationHeader authenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetSiteConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSiteConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumBlogrollsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBlogrollOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostBlogrollOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConfigEditingService() {
            this.Url = "http://localhost/omar/configeditingservice.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public authenticationHeader authenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSiteConfigCompletedEventHandler GetSiteConfigCompleted;
        
        /// <remarks/>
        public event UpdateSiteConfigCompletedEventHandler UpdateSiteConfigCompleted;
        
        /// <remarks/>
        public event EnumBlogrollsCompletedEventHandler EnumBlogrollsCompleted;
        
        /// <remarks/>
        public event GetBlogrollCompletedEventHandler GetBlogrollCompleted;
        
        /// <remarks/>
        public event PostBlogrollCompletedEventHandler PostBlogrollCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-newtelligence-com:dasblog:config-services/GetSiteConfig", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("siteConfig", Namespace="urn:schemas-newtelligence-com:dasblog:config-services")]
        public SiteConfig GetSiteConfig() {
            object[] results = this.Invoke("GetSiteConfig", new object[0]);
            return ((SiteConfig)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSiteConfig(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSiteConfig", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SiteConfig EndGetSiteConfig(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SiteConfig)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiteConfigAsync() {
            this.GetSiteConfigAsync(null);
        }
        
        /// <remarks/>
        public void GetSiteConfigAsync(object userState) {
            if ((this.GetSiteConfigOperationCompleted == null)) {
                this.GetSiteConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiteConfigOperationCompleted);
            }
            this.InvokeAsync("GetSiteConfig", new object[0], this.GetSiteConfigOperationCompleted, userState);
        }
        
        private void OnGetSiteConfigOperationCompleted(object arg) {
            if ((this.GetSiteConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiteConfigCompleted(this, new GetSiteConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-newtelligence-com:dasblog:config-services/UpdateSiteConfig", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void UpdateSiteConfig([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:newtelligence-com:dasblog:config", IsNullable=true)] SiteConfig siteConfig) {
            this.Invoke("UpdateSiteConfig", new object[] {
                        siteConfig});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateSiteConfig(SiteConfig siteConfig, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateSiteConfig", new object[] {
                        siteConfig}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateSiteConfig(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateSiteConfigAsync(SiteConfig siteConfig) {
            this.UpdateSiteConfigAsync(siteConfig, null);
        }
        
        /// <remarks/>
        public void UpdateSiteConfigAsync(SiteConfig siteConfig, object userState) {
            if ((this.UpdateSiteConfigOperationCompleted == null)) {
                this.UpdateSiteConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSiteConfigOperationCompleted);
            }
            this.InvokeAsync("UpdateSiteConfig", new object[] {
                        siteConfig}, this.UpdateSiteConfigOperationCompleted, userState);
        }
        
        private void OnUpdateSiteConfigOperationCompleted(object arg) {
            if ((this.UpdateSiteConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSiteConfigCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-newtelligence-com:dasblog:config-services/EnumBlogrolls", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services")]
        public string[] EnumBlogrolls() {
            object[] results = this.Invoke("EnumBlogrolls", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnumBlogrolls(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnumBlogrolls", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEnumBlogrolls(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EnumBlogrollsAsync() {
            this.EnumBlogrollsAsync(null);
        }
        
        /// <remarks/>
        public void EnumBlogrollsAsync(object userState) {
            if ((this.EnumBlogrollsOperationCompleted == null)) {
                this.EnumBlogrollsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumBlogrollsOperationCompleted);
            }
            this.InvokeAsync("EnumBlogrolls", new object[0], this.EnumBlogrollsOperationCompleted, userState);
        }
        
        private void OnEnumBlogrollsOperationCompleted(object arg) {
            if ((this.EnumBlogrollsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumBlogrollsCompleted(this, new EnumBlogrollsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-newtelligence-com:dasblog:config-services/GetBlogroll", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services")]
        public System.Xml.XmlElement GetBlogroll([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services")] string blogRollName) {
            object[] results = this.Invoke("GetBlogroll", new object[] {
                        blogRollName});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBlogroll(string blogRollName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBlogroll", new object[] {
                        blogRollName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndGetBlogroll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetBlogrollAsync(string blogRollName) {
            this.GetBlogrollAsync(blogRollName, null);
        }
        
        /// <remarks/>
        public void GetBlogrollAsync(string blogRollName, object userState) {
            if ((this.GetBlogrollOperationCompleted == null)) {
                this.GetBlogrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBlogrollOperationCompleted);
            }
            this.InvokeAsync("GetBlogroll", new object[] {
                        blogRollName}, this.GetBlogrollOperationCompleted, userState);
        }
        
        private void OnGetBlogrollOperationCompleted(object arg) {
            if ((this.GetBlogrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBlogrollCompleted(this, new GetBlogrollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-newtelligence-com:dasblog:config-services/PostBlogroll", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void PostBlogroll([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services")] string blogRollName, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services")] System.Xml.XmlElement blogRoll) {
            this.Invoke("PostBlogroll", new object[] {
                        blogRollName,
                        blogRoll});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostBlogroll(string blogRollName, System.Xml.XmlElement blogRoll, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostBlogroll", new object[] {
                        blogRollName,
                        blogRoll}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPostBlogroll(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void PostBlogrollAsync(string blogRollName, System.Xml.XmlElement blogRoll) {
            this.PostBlogrollAsync(blogRollName, blogRoll, null);
        }
        
        /// <remarks/>
        public void PostBlogrollAsync(string blogRollName, System.Xml.XmlElement blogRoll, object userState) {
            if ((this.PostBlogrollOperationCompleted == null)) {
                this.PostBlogrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostBlogrollOperationCompleted);
            }
            this.InvokeAsync("PostBlogroll", new object[] {
                        blogRollName,
                        blogRoll}, this.PostBlogrollOperationCompleted, userState);
        }
        
        private void OnPostBlogrollOperationCompleted(object arg) {
            if ((this.PostBlogrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostBlogrollCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services:auth-temp")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas-newtelligence-com:dasblog:config-services:auth-temp", IsNullable=false)]
    public partial class authenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:newtelligence-com:dasblog:config")]
    public partial class CrosspostSite {
        
        private System.Xml.XmlElement[] anyField;
        
        private string profileNameField;
        
        private string hostNameField;
        
        private int portField;
        
        private string endpointField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string blogidField;
        
        private string blognameField;
        
        private string[] allblognamesField;
        
        private string apitypeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileName {
            get {
                return this.profileNameField;
            }
            set {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string blogid {
            get {
                return this.blogidField;
            }
            set {
                this.blogidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string blogname {
            get {
                return this.blognameField;
            }
            set {
                this.blognameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] allblognames {
            get {
                return this.allblognamesField;
            }
            set {
                this.allblognamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string apitype {
            get {
                return this.apitypeField;
            }
            set {
                this.apitypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:newtelligence-com:dasblog:config")]
    public partial class ContentFilter {
        
        private System.Xml.XmlElement[] anyField;
        
        private string findField;
        
        private string replaceField;
        
        private bool isregexField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string find {
            get {
                return this.findField;
            }
            set {
                this.findField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isregex {
            get {
                return this.isregexField;
            }
            set {
                this.isregexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:newtelligence-com:dasblog:config")]
    public partial class SiteConfig {
        
        private System.Xml.XmlElement[] anyField;
        
        private string titleField;
        
        private string subtitleField;
        
        private string themeField;
        
        private string descriptionField;
        
        private string contactField;
        
        private string rootField;
        
        private string copyrightField;
        
        private int rssDayCountField;
        
        private int rssMainEntryCountField;
        
        private int rssEntryCountField;
        
        private bool enableRssItemFootersField;
        
        private string rssItemFooterField;
        
        private int frontPageDayCountField;
        
        private int frontPageEntryCountField;
        
        private bool categoryAllEntriesField;
        
        private string frontPageCategoryField;
        
        private bool alwaysIncludeContentInRSSField;
        
        private bool entryTitleAsLinkField;
        
        private bool notifyWebLogsDotComField;
        
        private bool notifyBloGsField;
        
        private bool obfuscateEmailField;
        
        private string notificationEMailAddressField;
        
        private bool sendCommentsByEmailField;
        
        private bool sendReferralsByEmailField;
        
        private bool sendTrackbacksByEmailField;
        
        private bool sendPingbacksByEmailField;
        
        private bool sendPostsByEmailField;
        
        private bool enableBloggerApiField;
        
        private bool enableCommentsField;
        
        private bool enableCommentApiField;
        
        private bool enableConfigEditServiceField;
        
        private bool enableEditServiceField;
        
        private bool enableAutoPingbackField;
        
        private bool showCommentCountField;
        
        private bool enableTrackbackServiceField;
        
        private bool enablePingbackServiceField;
        
        private bool enableStartPageCachingField;
        
        private bool enableBlogrollDescriptionField;
        
        private bool enableUrlRewritingField;
        
        private bool enableFtbField;
        
        private bool enableCrosspostsField;
        
        private bool useUserCultureField;
        
        private bool showItemDescriptionInAggregatedViewsField;
        
        private bool enableClickThroughField;
        
        private bool enableAggregatorBuggingField;
        
        private int displayTimeZoneIndexField;
        
        private bool adjustDisplayTimeZoneField;
        
        private string editPasswordField;
        
        private string contentDirField;
        
        private string logDirField;
        
        private string binariesDirField;
        
        private string smtpServerField;
        
        private bool enablePop3Field;
        
        private string pop3ServerField;
        
        private string pop3UsernameField;
        
        private string pop3PasswordField;
        
        private string pop3SubjectPrefixField;
        
        private int pop3IntervalField;
        
        private bool pop3InlineAttachedPicturesField;
        
        private int pop3InlinedAttachedPicturesThumbHeightField;
        
        private bool applyContentFiltersToWebField;
        
        private bool applyContentFiltersToRSSField;
        
        private bool enableXSSUpstreamField;
        
        private string xSSUpstreamEndpointField;
        
        private string xSSUpstreamUsernameField;
        
        private string xSSUpstreamPasswordField;
        
        private string xSSRSSFilenameField;
        
        private int xSSUpstreamIntervalField;
        
        private ContentFilter[] contentFiltersField;
        
        private CrosspostSite[] crosspostSitesField;
        
        private bool pop3DeleteAllMessagesField;
        
        private bool pop3LogIgnoredEmailsField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <remarks/>
        public string Theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
            }
        }
        
        /// <remarks/>
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        public int RssDayCount {
            get {
                return this.rssDayCountField;
            }
            set {
                this.rssDayCountField = value;
            }
        }
        
        /// <remarks/>
        public int RssMainEntryCount {
            get {
                return this.rssMainEntryCountField;
            }
            set {
                this.rssMainEntryCountField = value;
            }
        }
        
        /// <remarks/>
        public int RssEntryCount {
            get {
                return this.rssEntryCountField;
            }
            set {
                this.rssEntryCountField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableRssItemFooters {
            get {
                return this.enableRssItemFootersField;
            }
            set {
                this.enableRssItemFootersField = value;
            }
        }
        
        /// <remarks/>
        public string RssItemFooter {
            get {
                return this.rssItemFooterField;
            }
            set {
                this.rssItemFooterField = value;
            }
        }
        
        /// <remarks/>
        public int FrontPageDayCount {
            get {
                return this.frontPageDayCountField;
            }
            set {
                this.frontPageDayCountField = value;
            }
        }
        
        /// <remarks/>
        public int FrontPageEntryCount {
            get {
                return this.frontPageEntryCountField;
            }
            set {
                this.frontPageEntryCountField = value;
            }
        }
        
        /// <remarks/>
        public bool CategoryAllEntries {
            get {
                return this.categoryAllEntriesField;
            }
            set {
                this.categoryAllEntriesField = value;
            }
        }
        
        /// <remarks/>
        public string FrontPageCategory {
            get {
                return this.frontPageCategoryField;
            }
            set {
                this.frontPageCategoryField = value;
            }
        }
        
        /// <remarks/>
        public bool AlwaysIncludeContentInRSS {
            get {
                return this.alwaysIncludeContentInRSSField;
            }
            set {
                this.alwaysIncludeContentInRSSField = value;
            }
        }
        
        /// <remarks/>
        public bool EntryTitleAsLink {
            get {
                return this.entryTitleAsLinkField;
            }
            set {
                this.entryTitleAsLinkField = value;
            }
        }
        
        /// <remarks/>
        public bool NotifyWebLogsDotCom {
            get {
                return this.notifyWebLogsDotComField;
            }
            set {
                this.notifyWebLogsDotComField = value;
            }
        }
        
        /// <remarks/>
        public bool NotifyBloGs {
            get {
                return this.notifyBloGsField;
            }
            set {
                this.notifyBloGsField = value;
            }
        }
        
        /// <remarks/>
        public bool ObfuscateEmail {
            get {
                return this.obfuscateEmailField;
            }
            set {
                this.obfuscateEmailField = value;
            }
        }
        
        /// <remarks/>
        public string NotificationEMailAddress {
            get {
                return this.notificationEMailAddressField;
            }
            set {
                this.notificationEMailAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool SendCommentsByEmail {
            get {
                return this.sendCommentsByEmailField;
            }
            set {
                this.sendCommentsByEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendReferralsByEmail {
            get {
                return this.sendReferralsByEmailField;
            }
            set {
                this.sendReferralsByEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendTrackbacksByEmail {
            get {
                return this.sendTrackbacksByEmailField;
            }
            set {
                this.sendTrackbacksByEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendPingbacksByEmail {
            get {
                return this.sendPingbacksByEmailField;
            }
            set {
                this.sendPingbacksByEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendPostsByEmail {
            get {
                return this.sendPostsByEmailField;
            }
            set {
                this.sendPostsByEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableBloggerApi {
            get {
                return this.enableBloggerApiField;
            }
            set {
                this.enableBloggerApiField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableComments {
            get {
                return this.enableCommentsField;
            }
            set {
                this.enableCommentsField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableCommentApi {
            get {
                return this.enableCommentApiField;
            }
            set {
                this.enableCommentApiField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableConfigEditService {
            get {
                return this.enableConfigEditServiceField;
            }
            set {
                this.enableConfigEditServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableEditService {
            get {
                return this.enableEditServiceField;
            }
            set {
                this.enableEditServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableAutoPingback {
            get {
                return this.enableAutoPingbackField;
            }
            set {
                this.enableAutoPingbackField = value;
            }
        }
        
        /// <remarks/>
        public bool ShowCommentCount {
            get {
                return this.showCommentCountField;
            }
            set {
                this.showCommentCountField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableTrackbackService {
            get {
                return this.enableTrackbackServiceField;
            }
            set {
                this.enableTrackbackServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool EnablePingbackService {
            get {
                return this.enablePingbackServiceField;
            }
            set {
                this.enablePingbackServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableStartPageCaching {
            get {
                return this.enableStartPageCachingField;
            }
            set {
                this.enableStartPageCachingField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableBlogrollDescription {
            get {
                return this.enableBlogrollDescriptionField;
            }
            set {
                this.enableBlogrollDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableUrlRewriting {
            get {
                return this.enableUrlRewritingField;
            }
            set {
                this.enableUrlRewritingField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableFtb {
            get {
                return this.enableFtbField;
            }
            set {
                this.enableFtbField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableCrossposts {
            get {
                return this.enableCrosspostsField;
            }
            set {
                this.enableCrosspostsField = value;
            }
        }
        
        /// <remarks/>
        public bool UseUserCulture {
            get {
                return this.useUserCultureField;
            }
            set {
                this.useUserCultureField = value;
            }
        }
        
        /// <remarks/>
        public bool ShowItemDescriptionInAggregatedViews {
            get {
                return this.showItemDescriptionInAggregatedViewsField;
            }
            set {
                this.showItemDescriptionInAggregatedViewsField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableClickThrough {
            get {
                return this.enableClickThroughField;
            }
            set {
                this.enableClickThroughField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableAggregatorBugging {
            get {
                return this.enableAggregatorBuggingField;
            }
            set {
                this.enableAggregatorBuggingField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayTimeZoneIndex {
            get {
                return this.displayTimeZoneIndexField;
            }
            set {
                this.displayTimeZoneIndexField = value;
            }
        }
        
        /// <remarks/>
        public bool AdjustDisplayTimeZone {
            get {
                return this.adjustDisplayTimeZoneField;
            }
            set {
                this.adjustDisplayTimeZoneField = value;
            }
        }
        
        /// <remarks/>
        public string EditPassword {
            get {
                return this.editPasswordField;
            }
            set {
                this.editPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string ContentDir {
            get {
                return this.contentDirField;
            }
            set {
                this.contentDirField = value;
            }
        }
        
        /// <remarks/>
        public string LogDir {
            get {
                return this.logDirField;
            }
            set {
                this.logDirField = value;
            }
        }
        
        /// <remarks/>
        public string BinariesDir {
            get {
                return this.binariesDirField;
            }
            set {
                this.binariesDirField = value;
            }
        }
        
        /// <remarks/>
        public string SmtpServer {
            get {
                return this.smtpServerField;
            }
            set {
                this.smtpServerField = value;
            }
        }
        
        /// <remarks/>
        public bool EnablePop3 {
            get {
                return this.enablePop3Field;
            }
            set {
                this.enablePop3Field = value;
            }
        }
        
        /// <remarks/>
        public string Pop3Server {
            get {
                return this.pop3ServerField;
            }
            set {
                this.pop3ServerField = value;
            }
        }
        
        /// <remarks/>
        public string Pop3Username {
            get {
                return this.pop3UsernameField;
            }
            set {
                this.pop3UsernameField = value;
            }
        }
        
        /// <remarks/>
        public string Pop3Password {
            get {
                return this.pop3PasswordField;
            }
            set {
                this.pop3PasswordField = value;
            }
        }
        
        /// <remarks/>
        public string Pop3SubjectPrefix {
            get {
                return this.pop3SubjectPrefixField;
            }
            set {
                this.pop3SubjectPrefixField = value;
            }
        }
        
        /// <remarks/>
        public int Pop3Interval {
            get {
                return this.pop3IntervalField;
            }
            set {
                this.pop3IntervalField = value;
            }
        }
        
        /// <remarks/>
        public bool Pop3InlineAttachedPictures {
            get {
                return this.pop3InlineAttachedPicturesField;
            }
            set {
                this.pop3InlineAttachedPicturesField = value;
            }
        }
        
        /// <remarks/>
        public int Pop3InlinedAttachedPicturesThumbHeight {
            get {
                return this.pop3InlinedAttachedPicturesThumbHeightField;
            }
            set {
                this.pop3InlinedAttachedPicturesThumbHeightField = value;
            }
        }
        
        /// <remarks/>
        public bool ApplyContentFiltersToWeb {
            get {
                return this.applyContentFiltersToWebField;
            }
            set {
                this.applyContentFiltersToWebField = value;
            }
        }
        
        /// <remarks/>
        public bool ApplyContentFiltersToRSS {
            get {
                return this.applyContentFiltersToRSSField;
            }
            set {
                this.applyContentFiltersToRSSField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableXSSUpstream {
            get {
                return this.enableXSSUpstreamField;
            }
            set {
                this.enableXSSUpstreamField = value;
            }
        }
        
        /// <remarks/>
        public string XSSUpstreamEndpoint {
            get {
                return this.xSSUpstreamEndpointField;
            }
            set {
                this.xSSUpstreamEndpointField = value;
            }
        }
        
        /// <remarks/>
        public string XSSUpstreamUsername {
            get {
                return this.xSSUpstreamUsernameField;
            }
            set {
                this.xSSUpstreamUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string XSSUpstreamPassword {
            get {
                return this.xSSUpstreamPasswordField;
            }
            set {
                this.xSSUpstreamPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string XSSRSSFilename {
            get {
                return this.xSSRSSFilenameField;
            }
            set {
                this.xSSRSSFilenameField = value;
            }
        }
        
        /// <remarks/>
        public int XSSUpstreamInterval {
            get {
                return this.xSSUpstreamIntervalField;
            }
            set {
                this.xSSUpstreamIntervalField = value;
            }
        }
        
        /// <remarks/>
        public ContentFilter[] ContentFilters {
            get {
                return this.contentFiltersField;
            }
            set {
                this.contentFiltersField = value;
            }
        }
        
        /// <remarks/>
        public CrosspostSite[] CrosspostSites {
            get {
                return this.crosspostSitesField;
            }
            set {
                this.crosspostSitesField = value;
            }
        }
        
        /// <remarks/>
        public bool Pop3DeleteAllMessages {
            get {
                return this.pop3DeleteAllMessagesField;
            }
            set {
                this.pop3DeleteAllMessagesField = value;
            }
        }
        
        /// <remarks/>
        public bool Pop3LogIgnoredEmails {
            get {
                return this.pop3LogIgnoredEmailsField;
            }
            set {
                this.pop3LogIgnoredEmailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSiteConfigCompletedEventHandler(object sender, GetSiteConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiteConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiteConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SiteConfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SiteConfig)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateSiteConfigCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EnumBlogrollsCompletedEventHandler(object sender, EnumBlogrollsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumBlogrollsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumBlogrollsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBlogrollCompletedEventHandler(object sender, GetBlogrollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBlogrollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBlogrollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PostBlogrollCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591