@DOMAIN=https://localhost:5001


GET {{DOMAIN}}/.well-known/webfinger
Accept: text/html

###
GET {{DOMAIN}}/@blog
Accept: text/html

###
GET {{DOMAIN}}/users/poppastring
Accept: text/html

###
GET https://dotnet.social/users/poppastring/outbox?page=true
Accept: text/html