//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("dasBlog 4.0.0")]
[assembly: AssemblyDescription("dasBlog 4.0.0 ASP.NET Blogging Engine")]
[assembly: AssemblyProduct("dasBlog")]
[assembly: AssemblyCopyright("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("22F15D36-4E7E-4c9b-A79C-F0A2177EE97B")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: AssemblyFileVersion("4.0.0.0")]


